# Generated by Django 5.0.6 on 2024-08-15 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0004_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Ad_min.producttype'),
            preserve_default=False,
        ),
    ]
