# Generated by Django 5.0.6 on 2024-08-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0006_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productsize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Ad_min.productsize'),
            preserve_default=False,
        ),
    ]
