# Generated by Django 5.0.6 on 2024-08-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0010_product_productbrand_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
