# Generated by Django 5.0.6 on 2024-08-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0012_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='sub_image1',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sub_image2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sub_image3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sub_image4',
        ),
    ]
