# Generated by Django 5.0.6 on 2024-08-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0013_rename_sub_image1_productimage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
