# Generated by Django 5.0.6 on 2024-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0014_remove_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='type_status',
            field=models.BooleanField(default=True),
        ),
    ]
