# Generated by Django 5.0.6 on 2024-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0015_brand_brand_status_productsize_size_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='woasldk',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
