# Generated by Django 5.0.6 on 2024-09-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0016_product_woasldk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='woasldk',
        ),
    ]
