# Generated by Django 5.0.6 on 2024-09-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0017_remove_product_woasldk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percentage', models.FloatField()),
                ('expiration_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
