# Generated by Django 5.0.6 on 2024-09-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0021_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Ad_min.product'),
            preserve_default=False,
        ),
    ]
