# Generated by Django 5.0.6 on 2024-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0023_remove_productvariant_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
