# Generated by Django 5.0.6 on 2024-09-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0025_brandoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandoffer',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_offers', to='Ad_min.brand'),
            preserve_default=False,
        ),
    ]
