# Generated by Django 5.0.6 on 2024-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0029_alter_brandoffer_brand_alter_productoffer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_amount', models.IntegerField()),
                ('overall_discount', models.ImageField(upload_to='')),
                ('sales_count', models.ImageField(upload_to='')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
