# Generated by Django 5.0.6 on 2024-09-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0030_salesreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
