# Generated by Django 5.0.6 on 2024-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0031_delete_salesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_amount', models.IntegerField()),
                ('overall_discount', models.IntegerField()),
                ('sales_count', models.IntegerField()),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('order_id', models.IntegerField()),
                ('total_product', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('coupon_used', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
