# Generated by Django 5.0.6 on 2024-09-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0032_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='overall_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='overall_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
