# Generated by Django 5.0.6 on 2024-09-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0036_alter_salesreport_overall_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='total_product',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='user_name',
        ),
    ]
