# Generated by Django 5.0.6 on 2024-09-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0037_remove_salesreport_coupon_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='delivered_at',
        ),
    ]
