# Generated by Django 5.0.6 on 2024-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0039_delete_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
