# Generated by Django 5.0.6 on 2024-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_addresses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
