# Generated by Django 5.0.6 on 2024-08-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_cart_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variant',
        ),
    ]
