# Generated by Django 5.0.6 on 2024-08-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0012_product_status'),
        ('user', '0012_remove_cart_product_cart_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Ad_min.product'),
            preserve_default=False,
        ),
    ]
