# Generated by Django 5.0.6 on 2024-08-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0012_product_status'),
        ('user', '0017_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ad_min.product'),
            preserve_default=False,
        ),
    ]
