# Generated by Django 5.0.6 on 2024-08-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_orderitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
    ]
