# Generated by Django 5.0.6 on 2024-08-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0012_product_status'),
        ('user', '0023_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ad_min.productvariant'),
            preserve_default=False,
        ),
    ]
