# Generated by Django 5.0.6 on 2024-08-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_orderitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
    ]
