# Generated by Django 5.0.6 on 2024-08-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
