# Generated by Django 5.0.6 on 2024-08-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0013_rename_sub_image1_productimage_images_and_more'),
        ('user', '0027_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Ad_min.productimage'),
            preserve_default=False,
        ),
    ]
