# Generated by Django 5.0.6 on 2024-08-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0013_rename_sub_image1_productimage_images_and_more'),
        ('user', '0028_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ad_min.productimage'),
            preserve_default=False,
        ),
    ]
