# Generated by Django 5.0.6 on 2024-08-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_orderitem_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='images',
        ),
    ]
