# Generated by Django 5.0.6 on 2024-08-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_orderitem_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
    ]
