# Generated by Django 5.0.6 on 2024-08-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.order'),
            preserve_default=False,
        ),
    ]
