# Generated by Django 5.0.6 on 2024-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_orderaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
