# Generated by Django 5.0.6 on 2024-09-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0018_coupon'),
        ('user', '0035_alter_orderitem_order_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Ad_min.coupon'),
        ),
    ]
