# Generated by Django 5.0.6 on 2024-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_order_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
