# Generated by Django 5.0.6 on 2024-09-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_order_paid_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='razorpay_order_id',
        ),
    ]
