# Generated by Django 5.0.6 on 2024-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0027_product_brand_offer'),
        ('user', '0041_rename_razorpay_payment_id_order_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='Ad_min.product')),
            ],
        ),
    ]
