# Generated by Django 5.0.6 on 2024-09-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_wishlist_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='variant',
        ),
    ]
