# Generated by Django 5.0.6 on 2024-09-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_amount',
            field=models.IntegerField(default=0),
        ),
    ]
