# Generated by Django 5.0.6 on 2024-09-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_wallet_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
