# Generated by Django 5.0.6 on 2024-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_price',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
