# Generated by Django 5.0.6 on 2024-09-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_alter_order_total_amount_alter_orderitem_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='offer_price',
        ),
    ]
