# Generated by Django 5.0.6 on 2024-09-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad_min', '0040_coupon_maximum_amount_coupon_minimum_amount'),
        ('user', '0065_couponused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponused',
            name='Coupon',
        ),
        migrations.AddField(
            model_name='couponused',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ad_min.coupon'),
            preserve_default=False,
        ),
    ]
