# Generated by Django 5.0.6 on 2024-09-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_order_return_request_order_rreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rreason',
            new_name='reason',
        ),
    ]
