# Generated by Django 5.0.6 on 2024-09-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_rename_rreason_order_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reason',
        ),
    ]
