# Generated by Django 5.0.6 on 2024-09-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_transaction_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='typ',
            new_name='type',
        ),
    ]
