# Generated by Django 5.0.6 on 2024-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_rename_typ_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_request',
            field=models.BooleanField(default=False),
        ),
    ]
