# Generated by Django 5.0.6 on 2024-09-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_orderitem_return_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='return_request',
            new_name='item_return_request',
        ),
    ]
