# Generated by Django 5.0.6 on 2024-10-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_rename_return_request_orderitem_item_return_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(max_length=10),
        ),
    ]
